export const texts = {
    buttonShow: 'Show Task Text',
    apiHeader: 'Using data from links below: ',
    users: 'Users API: ',
    usersApi: 'https://fakestoreapi.com/users',
    carts: 'Carts API: ',
    cartsApi: 'https://fakestoreapi.com/carts/?startdate=2000-01-01&enddate=2023-04-07',
    products: 'Products API: ',
    productsApi: 'https://fakestoreapi.com/products',
    usersHeader: 'Implement a program which: ',
    firstTask: '1. Retrieves user, product and shopping cart data ;',
    secondTask: '2. Creates a data structure containing all available product categories and the total value of products of a given category;',
    thirdTask: '3. Finds a cart with the highest value, determines its value and full name of its owner;',
    fourthTask: '4. Finds the two users living furthest away from each other a desirable part of a given solution is also a set of tests to verify its correctness;',
}